add retries for request to uploadcare
StepicOrg/summary pull request #14
Opened 2017-03-09 11:39 UTC by kostya93

Проблема аналогичная этой https://github.com/StepicOrg/summary/pull/12, только с uploadcare
Решение также аналогичное.

2017-03-09 14:12 UTC, psviderski requested changes
Если решение аналогичное и код тот же, то лучше его вынести в куда-нибудь в утилс и переиспользовать.

2017-03-09 14:48 UTC, kostya93 commented
@psviderski убрал в utils.
Еще увеличил максимальный размер видео, такое нашлось в курсе по web-технологиям.

2017-03-10 06:27 UTC, dmitry-mukhin commented
Why not use `pyuploadcare`? Just curious.

2017-03-10 09:01 UTC, kostya93 commented
@dmitry-mukhin На самом деле у меня просто не возникло мысли гуглить библиотеку для того, чтобы сделать 1 запрос, поэтому я был не в курсе про `pyuploadcare`.

2017-03-10 11:58 UTC, psviderski approved these changes
👍

2017-03-10 12:02 UTC, merged