Add webserver
StepicOrg/summary pull request #4
Opened 2016-09-04 20:47 UTC by kostya93

2016-09-05 12:37 UTC, psviderski commented on tasks.py
> +logger.setLevel(logging.DEBUG)
Если это вся конфигурация логгинга, то этого недостаточно. info и debug логи все равно не будут выводиться. Можно сделать `logging.basicConfig` и переопределить в нем `level`.

2016-09-05 12:58 UTC, psviderski commented on tasks.py
> +    auth = HTTPBasicAuth(args.client_id, args.client_secret)
Очень хорошо работу с API стороннего сервиса заворачивать в клиентский класс, вот пример: https://github.com/rev112/playterminal/blob/master/games/utils/stepic_client.py#L19
Все авторизации, сессии с токеном, вызовы api-методов, обработка HTTP ошибок (важно!) инкапсулируются и снаружи остается только красивый интерфейс.

2016-09-06 10:01 UTC, psviderski commented on tasks.py
> +                             auth=auth)
Здесь не получается один раз авторизоваться и переиспользовать токен? Можно ли шарить в тасках `ProcessPoolExecutor` не только примитивные объекты , например, объект `client` для работы с api stepik?

2016-09-06 10:03 UTC, psviderski commented on tasks.py
> +def task(args):
`submit` и `task` — дефолтная терминология пула процессов, но лучше назвать чем-то более говорящим, чтобы из названия складывалась ассоциация, что сабмитим и что делает задача.

2016-09-06 10:57 UTC, psviderski commented on tasks.py
> +    steps = [lesson['steps'][args.step_number]] if args.step_number else lesson['steps']
Если `step_number` начинает с `1`, то здесь похоже надо добавить `- 1`. Если с `0`, то выше проверка на `> len(...)` должна быть `>= len`.

2016-09-06 11:07 UTC, psviderski commented on utils.py
> +class Args(object):
Удобно использовать встроенный тип `namedtuple` для таких вещей: https://docs.python.org/3.4/library/collections.html#collections.namedtuple

2016-09-06 11:21 UTC, psviderski commented on webserver.py
> +            step_number = None
Из документации похоже, что можно написать `self.get_argument('step_number', default=None)`.
Это нужно будет передавать параметр в виде query string к урлу. Не совсем удачный дизайн API, но для первого запуска сгодится, ничего можно пока не менять. Позже можно будет сделать json handler: http://tornado-json.readthedocs.io/en/latest/using_tornado_json.html и принимать json объект с параметрами.

2016-09-06 12:42 UTC, psviderski commented
Хорошо иметь функциональный тест, не обязательно быстрый, который запускает реальную проверку всей системы. Можно выбрать какой-нибудь реальный урок на Stepik и для него запускать проверку. Если будет пуш конспекта назад в Stepik, то это действие замокать и проверить, что именно отправляется.

2016-09-26 11:45 UTC, kostya93 commented on tasks.py
> +logger.setLevel(logging.DEBUG)
@psviderski торнадовский раннер делает что-то, что логи работают.

2016-09-26 12:30 UTC, kostya93 commented on tasks.py
> +                             auth=auth)
@psviderski так у нас же каждый запрос может быть со своим `(client_id, client_secret)` , т.е. можно наверно вынести авторизацию из такси, т.е. делать ее в main треде сразу при получении запроса, предварительно проверяя, нет ли у нас токена для данной пары `(client_id, client_secret)` и авторизовываться только если нету, а в таксу передавать уже `client` , но как-то это неочень, ну либо я чет не так понял, что ты имеешь ввиду.

2016-09-28 08:30 UTC, psviderski commented on tasks.py
> +                             auth=auth)
А зачем на каждый раз в запросах передавать `client_id` и `client_secret`? Так же, как `upload_care_pub_key` и `yandex_speeck_kit_key` — это же все настройки сервиса, которые можно один раз задать на старте и использовать. Из запроса нам нужно узнать только урок со стэпом.
Конфигурацию в данном случае удобно задавать с помощью переменных окружения: https://12factor.net/config, полезно прочитать и другие принципы The twelve-factor app.

В edy мы используем https://github.com/joke2k/django-environ
Можно по такому же принципы использовать кусок из нее: https://github.com/rconradharris/envparse
Вот тут еще один пример, как я давно делал разделение настроек на base, local и docker: https://github.com/bioinf/rnr-mal/blob/master/mal/settings/docker.py

2016-09-28 20:09 UTC, psviderski requested changes

2016-09-28 20:09 UTC, psviderski commented on Dockerfile.local
> +FROM ubuntu:14.04
Не запаривайся насчет Dockerfile, я сделаю, чтобы было похоже на наши существующие сборки.

2016-09-28 20:09 UTC, psviderski commented on utils.py
> +        if step_number and (not step_number.isdigit() or not (1 <= int(step_number) <= len(lesson['steps']))):
Валидации того, что `step_number` — это число здесь быть не должно. Метод `get_steps` мы вызываем сами и не должны себя проверять. Когда получили значение в запросе или из командной строки, тогда и проверили его, а здесь уже точно число или None ожидаем.

2016-09-28 20:09 UTC, psviderski commented on tests.py
> +from secret import CLIENT_ID, CLIENT_SECRET, UPLOAD_CARE_PUB_KEY, YANDEX_SPEECH_KIT_KEY
Кто такой `secret`?

2016-09-28 20:09 UTC, psviderski commented on tests.py
> +        status, _ = list(new_send_response.call_args)
Результат ведь самое важно, что нужно проверить, чтобы протестировать работу распознавания видео и дампа текстовых шагов. Например, проверить, что там содержится строчка из видео. Или текст, если это текстовый шаг.

2016-10-03 18:02 UTC, psviderski approved these changes

2016-10-10 10:00 UTC, merged