Feature/send result to wiki
StepicOrg/summary pull request #5
Opened 2016-11-07 13:34 UTC by kostya93

2016-11-07 20:55 UTC, psviderski requested changes

2016-11-07 20:55 UTC, psviderski commented on constants.py
> +WIKI_BASE_URL = 'http://172.17.0.4'
Это скорее настройка для `settings.py`, чем константа, как и `STEPIK_BASE_URL`.

2016-11-07 20:55 UTC, psviderski commented on constants.py
> +                            '[[Category:Lessons]]'
Часто такие разбитые строки берут в скобки, чтобы не писать бэкслэши: http://stackoverflow.com/a/10660443

2016-11-07 20:55 UTC, psviderski commented on utils.py
> +        return title, steps, lesson_wiki_url
Лучше не делай результат кортежем, когда много разнородных элементов. Нагляднее сделать `dict` с говорящими ключами, так будет одно самодокументируемое возвращаемое значение, которое понятно как использовать.

2016-11-07 20:55 UTC, psviderski commented on utils.py
> +        except KeyError:
Что из этого блока кидает `KeyError`? Хорошо стараться локализировать место возникновения исключения в try/except.

2016-11-07 20:55 UTC, psviderski commented on utils.py
> +        self.token = self.session.get(action='query', meta='tokens')['query']['tokens']['csrftoken']
Наверняка во время инициализации этого клиента может возникнуть проблема с сетью и вики будет недоступна. Логин может быть тоже неуспешным.
Токен один можно переиспользовать для многих запросов?

2016-11-07 20:55 UTC, psviderski commented on utils.py
> +        # TODO: send result to Stepik
Исключения в `WikiClient` оборвут выполнение воркер-процесса и никто не узнает, что стало с конспектом: то ли он еще генерируется, то ли что-то сломалось. Если поломалось хранилище (wiki), это нормально, всякое бывает, в Stepik нужно сказать, что мы не смогли сгенерить, что-то пошло не так, попробуйте еще раз. Т.е. хорошо на стороне Stepik понимать, что можно запускать генерацию конспекта еще раз, т.к. прошлый запуск был неуспешен.
И таких неудачных мест очень много в этом сервисе, поскольку зависим от кучи сторонних сервисов, которые живут своей не всегда стабильной жизнью. Простая и надежная тактика -- на самом верхнем уровне собрать исключения и всегда репортить результат.

2016-11-07 20:55 UTC, psviderski commented on utils.py
> +            url = wiki_client.create_page_for_step(step_id, position, content, lesson_title, lesson_id)
Здесь похоже напрашивается структурку какую-то завести, чтобы не перебрасывать кучу одиночных аргументов из одного места в другое. Например опять сгодится простой `dict`: `result['synopsis_by_steps'] ` сделать списком словарей `step_synopsis`, которые описывают конспект для шага. Этот же `step_synopsis` передаешь в `create_page_for_step`, который знает, что делать с этой структурой. Снаружи в `send_response` мы вообще можем ничего не знать про ее внутренности.
Пока `dict` справляется с тем, чтобы хранить все данные, используем его. Если потом структура усложнится, потребуются дополнительные методы, то можно будет сделать отдельный класс для нее. Но при этом здесь в `send_response` никаких изменений не нужно будет делать.

2016-11-07 20:55 UTC, psviderski commented on utils.py
> +def send_response(status, result):
Нужно еще написать интеграционный тест, который проверяет созданную структуру в wiki, чтобы дальше можно было безопасно рефакторить код.

2016-11-14 08:16 UTC, kostya93 commented on utils.py
> +        return title, steps, lesson_wiki_url
@psviderski да, изначально я писал везде словари, но потом получается, чтобы достать нужно значение приходится писать что-то такое https://github.com/StepicOrg/summary/blob/master/tests.py#L18-L23

2016-11-14 08:26 UTC, kostya93 commented on utils.py
> +        self.token = self.session.get(action='query', meta='tokens')['query']['tokens']['csrftoken']
@psviderski Токен можно использовать.
Вот что пишут тут [Manual:Edit_token](https://www.mediawiki.org/wiki/Manual:Edit_token) :
`The edit token returned by the server can be reused multiple times for different edit operations. The token is only valid for a specific period of time. API call with a stale token will return a badtoken error. In this case it is necessary to get a new edit token from the server before retrying the operation.`

2016-11-14 08:34 UTC, kostya93 commented on utils.py
> +        # TODO: send result to Stepik
@psviderski Но пока мы никак не храним на стэпике то, что создание конспекта вообще запущено, добавить сюда [EDY-5677](https://vyahhi.myjetbrains.com/youtrack/issue/EDY-5677) кроме хранения соответствия еще флаг о том, что создание конспекта запущено ? и еще тогда хорошо бы помнить кто его запустил, чтобы понятно было кому сообщать о результате.

2016-11-14 08:43 UTC, kostya93 commented on constants.py
> +WIKI_BASE_URL = 'http://172.17.0.4'
@psviderski Но тогда и `WIKI_API_PATH` ? он как бы тоже может меняться, у той же википедии он `w/api.php`, а не `api.php` как у меня сейчас.

2016-11-14 08:53 UTC, kostya93 commented on constants.py
> +                            '[[Category:Lessons]]'
@psviderski Сделал через [textwrap.deden()](https://docs.python.org/3.4/library/textwrap.html#textwrap.dedent) по аналогии с https://github.com/bioinf/edy/blob/develop/apps/telegram_bot/constants.py#L49-L60

2016-11-14 09:29 UTC, kostya93 commented on utils.py
> +        # TODO: send result to Stepik
@psviderski И еще, по поводу исключений в `WikiClient`. На верхнем уровне я естественно ловлю только свои исключения, т.е. `CreateSynopsisError`, а `WikiClient` бросается исключениями типа `mwapi.errors.LoginError` и `mwapi.errors.APIError`, значит где-то нужно их поймать и обернуть в `CreateSynopsisError`. Вопрос в том, где это делать, либо в классе `WikiClient`, каждый раз когда вызываются методы библиотеки `mwapi` , которые бросают исключения. Либо там, где уже используется объект класса `WikiClient` ?

2016-11-14 13:31 UTC, kostya93 commented
@psviderski Вроде все исправил.

2016-11-14 14:50 UTC, psviderski commented on utils.py
> +        # TODO: send result to Stepik
4-5) прокомментировал в задаче.
Исключения можно собрать в `WikiClient` и бросить свои, `WikiError`, унаследованный от `CreateSynopsisError`. Если выше в коде нигде не нужно разделять, что упало именно из-за проблем с вики, то можно кидать сразу базовый `CreateSynopsisError`.

2016-11-14 14:53 UTC, psviderski commented on constants.py
> +WIKI_BASE_URL = 'http://172.17.0.4'
Да, разумно, можно указать дефолтные значения, если настройка не определена.

2016-11-14 22:12 UTC, psviderski commented on utils.py
> +        return title, steps, lesson_wiki_url
Это не супер криминал, что ж поделаешь, что структура довольно вложенная получилась. Хотя две вложенные итерации стоит избежать.
Последняя итерация:
```
                    for content_type, content in content_obj.items():
                        if content_type == IS_TEXT and phrase in content:
                            return
```
Не очень удачно, мне кажется, делать словарь всегда с одним ключом. Удобнее использовать такой формат:
```
{
    'is_text': True/False,
    'content': content,
}
```
Если типов будет больше, чем два, то `is_text` можно превратить в `type'. И это все один объект, структуру которого можно усложнять.

То же самое с итерацией
```
 for step_id, synopsis in synopsis_for_step.items():
```
dict с одним ключом `{step: content}`. Лучше 2 ключа, т.к. понятно сразу без итераций, где брать данные.

2016-11-21 09:41 UTC, kostya93 commented on utils.py
> +        return title, steps, lesson_wiki_url
Сделал.
Только для вместо `'is_text': True/False`, сразу использую `'type': IS_TEXT/IS_IMG`, мне кажется так понятнее, а места столько же занимает.

2016-11-21 09:41 UTC, kostya93 commented on utils.py
> +        except KeyError:
Уже ничего, убрал это.

2016-11-21 09:43 UTC, kostya93 commented on utils.py
> +def send_response(status, result):
Сделал.
Теперь есть 2 теста. Первый берет со стэпика шаг с видео, распознает его и проверяет что все правильно распозналось. Второй берет шаг с текстом, распознает его(т.е. просто берет содержимое), постит на вики и проверяет что все правильно запостилось.

2016-11-21 09:43 UTC, kostya93 commented on utils.py
> +            url = wiki_client.create_page_for_step(step_id, position, content, lesson_title, lesson_id)
сделал.

2016-11-21 09:44 UTC, kostya93 commented on utils.py
> +        # TODO: send result to Stepik
сделал.

2016-11-21 09:45 UTC, kostya93 commented
@psviderski Вроде все исправил.

2016-11-21 11:25 UTC, psviderski commented on constants.py
> +IS_IMG = 'img'
Если сделали типом, то можно оформить константы в что-то типа енама как здесь: https://github.com/bioinf/edy/blob/develop/apps/telegram_bot/constants.py#L71
Префикс `IS_` очень странно здесь в константе выглядит, в булевой переменной или функции имеет смысл.

2016-11-21 12:40 UTC, psviderski commented
OK

2016-11-21 16:36 UTC, kostya93 commented
Исправил константы и еще один словарь.

2016-11-21 16:39 UTC, merged